#!/usr/bin/env python3
"""gc packman update — update packs to latest compatible versions."""

import hashlib
import os
import shutil
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "scripts"))
from common import (
    pack_toml_path, pack_lock_path, packs_cache_dir,
    load_taps, taps_cache_dir,
    git, git_tags, git_rev_parse,
    resolve_version,
    read_toml_simple, write_toml_simple,
)


def content_hash(directory):
    """Compute SHA-256 hash of all files in a directory."""
    paths = []
    for root, dirs, files in os.walk(directory):
        dirs[:] = [d for d in dirs if d != ".git"]
        for f in files:
            full = os.path.join(root, f)
            rel = os.path.relpath(full, directory)
            paths.append(rel)
    paths.sort()

    h = hashlib.sha256()
    for rel in paths:
        data = open(os.path.join(directory, rel), "rb").read()
        h.update(rel.encode())
        h.update(b"\x00")
        h.update(data)
        h.update(b"\x00")
    return h.hexdigest()


def main():
    args = sys.argv[1:]
    target_pack = args[0] if args else None

    toml_path = pack_toml_path()
    lock_path = pack_lock_path()

    config = read_toml_simple(toml_path) if os.path.exists(toml_path) else {}
    lock = read_toml_simple(lock_path) if os.path.exists(lock_path) else {}

    imports = config.get("imports", {})
    locked = lock.get("packs", {})

    if not imports:
        print("No packs imported.")
        return

    names = [target_pack] if target_pack else sorted(imports.keys())
    updated = False

    for name in names:
        if name not in imports:
            print(f"  {name}: not in imports, skipping", file=sys.stderr)
            continue

        imp = imports[name]
        lck = locked.get(name, {})

        tap_name = imp.get("tap", lck.get("tap", ""))
        constraint = imp.get("version", "")
        locked_ver = lck.get("version", "")

        if not tap_name:
            print(f"  {name}: no tap, skipping")
            continue

        tap_cache = os.path.join(taps_cache_dir(), tap_name)
        if not os.path.isdir(tap_cache):
            print(f"  {name}: tap \"{tap_name}\" not cached, skipping")
            continue

        # Fetch latest tags
        git("fetch", "origin", cwd=tap_cache)

        tags = git_tags(cwd=tap_cache)
        best = resolve_version(tags, name, constraint if constraint else None)

        if not best:
            print(f"  {name}: no matching version found")
            continue

        latest_ver, tag = best
        if latest_ver == locked_ver:
            print(f"  {name}: v{locked_ver} (up to date)")
            continue

        print(f"  {name}: v{locked_ver} \u2192 v{latest_ver}")

        # Checkout and copy
        git("checkout", "--force", ".", cwd=tap_cache, check=False)
        git("checkout", tag, cwd=tap_cache, check=False)

        dest = os.path.join(packs_cache_dir(), name)
        if os.path.exists(dest):
            shutil.rmtree(dest)

        src = os.path.join(tap_cache, name)
        if os.path.isdir(src):
            shutil.copytree(src, dest, ignore=shutil.ignore_patterns(".git"))
        elif os.path.isfile(os.path.join(tap_cache, "pack.toml")):
            shutil.copytree(tap_cache, dest, ignore=shutil.ignore_patterns(".git"))
        else:
            print(f"  {name}: pack directory not found at tag {tag}", file=sys.stderr)
            continue

        commit = git_rev_parse(tap_cache)
        chash = content_hash(dest)

        # Update lock
        taps = load_taps()
        tap_url = taps.get(tap_name, {}).get("url", lck.get("source", ""))

        locked[name] = {
            "tap": tap_name,
            "version": latest_ver,
            "source": tap_url,
            "ref": tag,
            "commit": commit,
            "hash": f"sha256:{chash}",
        }
        updated = True

    if updated:
        lock["packs"] = locked
        write_toml_simple(lock_path, lock,
                          header="Auto-generated by gc packman. Commit for reproducibility.")
        print("\n  Updated pack.lock")
    else:
        print("\nNothing to update.")


if __name__ == "__main__":
    main()
